# Site settings
title: Always learning, or at least trying
email: jeanrodriguez24@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This are some of my findings as I try to learn as much as I can.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jmrodriguez24.github.io" # the base hostname & protocol for your site
twitter_username: jmrodriguez24
github_username:  JMRodriguez24

# Build settings
markdown: kramdown
